# Site settings
title:          Paul Buckley's Site
description:    "Paul Buckley's personal website "
baseurl:        ""
url:            "paulbuckley.me"

# https://jekyllrb.com/docs/configuration/options/
timezone: America/Los_Angeles

# Available style options based on catppuccin: latte, frappe, macchiato, mocha
style_light: latte 
style_dark: macchiato

#include pages
include:
  - _pages

# Assets
sass:
  sass_dir:     /assets/css/_sass
  style:        compressed

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
